const fs = require('fs');
const path = require('path');
const axios = require('axios');

// 确保目录存在
const taskDir = path.join(__dirname, 'data/tasks');
if (!fs.existsSync(taskDir)) fs.mkdirSync(taskDir, { recursive: true });

const scriptContent = `
const axios = require('axios');
const fs = require('fs');
const path = require('path');

const BRAVE_KEY = process.env.BRAVE_SEARCH_API_KEY;
if (!BRAVE_KEY) { 
    console.error("❌ 错误: 缺少 BRAVE_SEARCH_API_KEY"); 
    process.exit(1); 
}

const today = new Date().toISOString().split('T')[0];
// 简报存储位置
const reportDir = path.join(__dirname, '../briefings'); 
if (!fs.existsSync(reportDir)) fs.mkdirSync(reportDir, { recursive: true });
const reportFile = path.join(reportDir, \`\${today}.md\`);

async function search(query) {
    try {
        console.log(\`🔍 正在搜索: \${query}...\`);
        const res = await axios.get('https://api.search.brave.com/res/v1/web/search', {
            params: { q: query, count: 5 },
            headers: { 'X-Subscription-Token': BRAVE_KEY, 'Accept': 'application/json' }
        });
        return res.data.web.results || [];
    } catch (e) {
        console.error(\`搜索失败: \${e.message}\`);
        return [];
    }
}

async function run() {
    console.log("⚡ 开始生成每日简报...");
    
    // 1. 获取新闻
    const news = await search(\`latest LLM AI agent news \${today}\`);
    
    // 2. 获取 GitHub 趋势 (尝试搜索相关列表或仓库)
    const github = await search(\`trending github repositories LLM agents \${today}\`);
    
    let content = \`# 🌅 每日早报: \${today}\\n\\n\`;
    content += \`> 早上好，小猫。这是今天的数字海洋潮汐报告。\\n\\n\`;
    
    content += \`## 🗞️ Agent & LLM 新闻\\n\`;
    if (news.length > 0) {
        news.forEach(n => content += \`- **[\${n.title}](\${n.url})**\\n  \${n.description}\\n\`);
    } else {
        content += \`- (今日暂无重大新闻抓取结果)\\n\`;
    }
    
    content += \`\\n## 🐙 GitHub 热门项目 (相关)\\n\`;
    if (github.length > 0) {
        github.forEach(n => content += \`- **[\${n.title}](\${n.url})**\\n  \${n.description}\\n\`);
    } else {
        content += \`- (未发现特定热门项目)\\n\`;
    }
    
    content += \`\\n---\\n*Generated by Aven's Automata at \${new Date().toLocaleTimeString()}*\\n\`;
    
    // 写入文件
    fs.writeFileSync(reportFile, content);
    console.log(\`✅ 简报已生成: \${reportFile}\`);
    console.log(content);
}

run();
`;

// 写入脚本文件
fs.writeFileSync('data/tasks/daily_briefing.js', scriptContent);
console.log("脚本已创建: data/tasks/daily_briefing.js");
